### ISSUE TITLE
ci machine reporting  out of storage

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/monarch-devops#54]
Jenkins fails

```
Caused by: java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at java.io.BufferedWriter.flush(BufferedWriter.java:254)
	at hudson.util.AtomicFileWriter.flush(AtomicFileWriter.java:91)
	at com.thoughtworks.xstream.core.util.QuickWriter.flush(QuickWriter.java:75)
	... 102 more

```

**Comment by jnguyenx** [comment]
That happened quickly... I'm doing some tests for the golr loader and that
took a lot of disk space. I've deleted some files for now.
