### ISSUE TITLE
More biolink api oddities

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-devops#67]
http://api.monarchinitiative.org/api

 1. A lot of the routes in the swagger UI don't open up when you click them. E.g the ones under /ontol/
 2. This gives a 502 http://api.monarchinitiative.org/api/ontol/subgraph/pato/PATO%3A0000058 (works on my local set up)

Note sure if these are related. 2 is the more serious. I suspect this is to do with the recent addition of cachier for persistent memoization. See https://pypi.python.org/pypi/Cachier/0.1.26 by default is caches in ~/.cachier - perhaps not available?

is there a way I can debug this myself? The log here is not revealing http://ci.monarchinitiative.org/job/start-biolink-api-dev/43/console - should I ssh in?

**Comment by cmungall** [comment]
Hmm, number 2 is now magically fixed. 1 is still an issue but this is annoying but less serious

**Comment by jnguyenx** [comment]
I don't really know for 1. I had a look a the logs, I copies the stacktrace at the end. For now the logs exist only on the VM at `monarch-api:/var/log/supervisor`, but I'll setup graylog for this service to centralize.

For 2, it's an encoding issue, probably from swagger or flask. Replacing the slash with a dash on this line solves the issue:
https://github.com/biolink/biolink-api/blob/master/biolink/api/ontol/endpoints/slimmer.py#L13


Stacktrace:
```
monarchapi-stdout---supervisor-jduWHH.log:20830523:[2017-02-18 19:06:35,622] ERROR in app: Exception on /api/ontol/subgraph/pato/PATO:0000058 [GET]
monarchapi-stdout---supervisor-jduWHH.log-20830620-Traceback (most recent call last):
monarchapi-stdout---supervisor-jduWHH.log-20830655-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
monarchapi-stdout---supervisor-jduWHH.log-20830758-    response = self.full_dispatch_request()
monarchapi-stdout---supervisor-jduWHH.log-20830802-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
monarchapi-stdout---supervisor-jduWHH.log-20830918-    rv = self.handle_user_exception(e)
monarchapi-stdout---supervisor-jduWHH.log-20830957-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/flask_restplus/api.py", line 557, in error_router
monarchapi-stdout---supervisor-jduWHH.log-20831072-    return original_handler(e)
monarchapi-stdout---supervisor-jduWHH.log-20831103-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
monarchapi-stdout---supervisor-jduWHH.log-20831224-    return cors_after_request(app.make_response(f(*args, **kwargs)))
monarchapi-stdout---supervisor-jduWHH.log-20831293-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
monarchapi-stdout---supervisor-jduWHH.log-20831409-    reraise(exc_type, exc_value, tb)
monarchapi-stdout---supervisor-jduWHH.log-20831446-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
monarchapi-stdout---supervisor-jduWHH.log-20831550-    raise value
monarchapi-stdout---supervisor-jduWHH.log-20831566-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
monarchapi-stdout---supervisor-jduWHH.log-20831682-    rv = self.dispatch_request()
monarchapi-stdout---supervisor-jduWHH.log-20831715-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
monarchapi-stdout---supervisor-jduWHH.log-20831826-    return self.view_functions[rule.endpoint](**req.view_args)
monarchapi-stdout---supervisor-jduWHH.log-20831889-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/flask_restplus/api.py", line 313, in wrapper
monarchapi-stdout---supervisor-jduWHH.log-20831999-    resp = resource(*args, **kwargs)
monarchapi-stdout---supervisor-jduWHH.log-20832036-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/flask/views.py", line 84, in view
monarchapi-stdout---supervisor-jduWHH.log-20832135-    return self.dispatch_request(*args, **kwargs)
monarchapi-stdout---supervisor-jduWHH.log-20832185-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
monarchapi-stdout---supervisor-jduWHH.log-20832308-    resp = meth(*args, **kwargs)
monarchapi-stdout---supervisor-jduWHH.log-20832341-  File "/opt/biolink-api-master/biolink/api/ontol/endpoints/subgraph.py", line 39, in get
monarchapi-stdout---supervisor-jduWHH.log-20832431-    g = get_digraph(ontol, ['subClassOf', 'BFO:0000050'], True)
monarchapi-stdout---supervisor-jduWHH.log-20832495-  File "/opt/biolink-api-master/obographs/sparql2ontology.py", line 42, in get_digraph
monarchapi-stdout---supervisor-jduWHH.log-20832582-    for (s,p,o) in get_edges(ont):
monarchapi-stdout---supervisor-jduWHH.log-20832617-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/cachier/core.py", line 520, in func_wrapper
monarchapi-stdout---supervisor-jduWHH.log-20832726-    return _calc_entry(core, key, func, args, kwds)
monarchapi-stdout---supervisor-jduWHH.log-20832778-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/cachier/core.py", line 413, in _calc_entry
monarchapi-stdout---supervisor-jduWHH.log-20832886-    func_res = func(*args, **kwds)
monarchapi-stdout---supervisor-jduWHH.log-20832921-  File "/opt/biolink-api-master/obographs/sparql2ontology.py", line 56, in get_edges
monarchapi-stdout---supervisor-jduWHH.log-20833006-    edges = [(c,SUBCLASS_OF, d) for (c,d) in fetchall_isa(ont)]
monarchapi-stdout---supervisor-jduWHH.log-20833070-  File "/opt/biolink-api-master/obographs/sparql2ontology.py", line 139, in fetchall_isa
monarchapi-stdout---supervisor-jduWHH.log-20833159-    bindings = run_sparql(query)
monarchapi-stdout---supervisor-jduWHH.log-20833192-  File "/opt/biolink-api-master/obographs/sparql2ontology.py", line 109, in run_sparql
monarchapi-stdout---supervisor-jduWHH.log-20833279-    results = sparql.query().convert()
monarchapi-stdout---supervisor-jduWHH.log-20833318-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/SPARQLWrapper/Wrapper.py", line 601, in query
monarchapi-stdout---supervisor-jduWHH.log-20833429-    return QueryResult(self._query())
monarchapi-stdout---supervisor-jduWHH.log-20833467-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/SPARQLWrapper/Wrapper.py", line 581, in _query
monarchapi-stdout---supervisor-jduWHH.log-20833579-    raise e
monarchapi-stdout---supervisor-jduWHH.log-20833591-  File "/opt/biolink-api-master/venv/lib/python3.5/site-packages/SPARQLWrapper/Wrapper.py", line 571, in _query
monarchapi-stdout---supervisor-jduWHH.log-20833703-    response = urlopener(request)
monarchapi-stdout---supervisor-jduWHH.log-20833737-  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
monarchapi-stdout---supervisor-jduWHH.log-20833805-    return opener.open(url, data, timeout)
monarchapi-stdout---supervisor-jduWHH.log-20833848-  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
monarchapi-stdout---supervisor-jduWHH.log-20833913-    response = meth(req, response)
monarchapi-stdout---supervisor-jduWHH.log-20833948-  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
monarchapi-stdout---supervisor-jduWHH.log-20834022-    'http', request, response, code, msg, hdrs)
monarchapi-stdout---supervisor-jduWHH.log-20834070-  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
monarchapi-stdout---supervisor-jduWHH.log-20834136-    return self._call_chain(*args)
monarchapi-stdout---supervisor-jduWHH.log-20834171-  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
monarchapi-stdout---supervisor-jduWHH.log-20834243-    result = func(*args)
monarchapi-stdout---supervisor-jduWHH.log-20834268-  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
monarchapi-stdout---supervisor-jduWHH.log-20834347-    raise HTTPError(req.full_url, code, msg, hdrs, fp)
monarchapi-stdout---supervisor-jduWHH.log-20834402-urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
```

**Comment by jnguyenx** [comment]
For 2, it works when the server is run locally. It's an encoding issue either at the nginx or the gunicorn layer.

**Comment by jnguyenx** [comment]
See https://github.com/biolink/biolink-api/issues/30
